osx_image: xcode7.1
language: objective-c
before_install:
  - gem install cocoapods xcpretty obcd slather --verbose --no-document
podfile: GTScrollNavigationBarExample/Podfile
env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
script:
  - set -o pipefail && xcodebuild -workspace GTScrollNavigationBarExample/GTScrollNavigationBarExample.xcworkspace
    -scheme GTScrollNavigationBarExample -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6s"
    GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES clean test | xcpretty -c
  - pod lib lint --quick
  - obcd --path GTScrollNavigationBar find HeaderStyle
after_success: slather
